### ISSUE TITLE
Support IBFT consensus in quorum-toolbox

### ISSUE THREAD

**Issue by hayorov** [chainstack/quorum-toolbox#7]
- [x] [Test Quorum pre-provided IBFT network for better understanding](https://github.com/chainstack/quorum-toolbox/issues/8)
- [ ] [Implement IBFT artifacts creation in quorum-toolbox](https://github.com/chainstack/quorum-toolbox/issues/9)
- [ ] [Extend quorum-node chart with IBFT consensus option](https://github.com/chainstack/helm-charts/issues/46)
